RMI-PACTA/pacta-dashboard-svelte

- .github/workflows/deploy.yml
- package-lock.json
- package.json
- src/routes/+layout.ts
- svelte.config.js
- **gains adapter-static**
- **build site statically**
- **set-up to deploy using GitHub actions**
> feat: make site static, and deploy to GH pages

- src/routes/portfolio_view.svelte
Add divs and invoke techmix in portfolio overview
> Show techmix in overview

- src/routes/company_view.svelte
- src/routes/sector_view.svelte
Add landing pages for company-level and sector-level views. 
The mechanics are not fully fleshed out yet but it will come later when I wire up all selectors. For now I hide them with class 'hidden' once the user clicked a button but in the end we might need another solution to preserve the state of the component when another tab is clicked (currently it is back to the landing page each time the tab is changed).
> Add landing pages

- src/js/time_line.js
- src/routes/sector_view.svelte
Update emission intensity so that it is sized to the size of the div and it works with global filters.
> Feat: update emission intensity - auto re-size and remove built-in filters

- src/routes/sector_view.svelte
Relates to #30 
In this PR I made the scenario parameter selector data-driven and I add a pop-up informing user to each plot the scenario choice applies.
> Data driven scenario

- src/routes/sector_view.svelte
Make allocation method selector data-driven. This selector is dependent on selection of:
* asset class
> Allocation method data-driven

- src/js/pie_exploded.js
- src/routes/portfolio_view.svelte
This PR:
* re-organizes portfolio level view
* modifies pie annotation text slightly
NOTE: 
* table does not look great at the moment but I leave improving of it's layout for another PR #53 
* consider if map should be removed from the view as it requires selectors as potentially the only plot in this view #54
> Portfolio layout in divs

- src/js/company_bubble.js
- src/routes/company_view.svelte
Company bubble chart re-sizes to the div size.
NOTE: the placement of all elements is not ideal yet but for the time being I leave it as it and fine tune later once I work on the styling and the layout of this page is clear.
> Company bubble resizing

- src/js/createErrorMessageDiv.js
- src/js/pie_exploded.js
- src/routes/portfolio_view.svelte
- src/routes/sector_view.svelte
Implement error handling for two cases:
* parameter choices yield empty data
* plot throws an error
NOTE: currently the visual side of the error message is not the most appealing but I decided not to focus on it too much right now. If I have time I will try to beautify everything as much as possible at the end of the project. The error handling function is a extracted into a seperate file so it shold be easy to change the visual side of it if we want.
NOTE 2: there are styling changes to pie code unrelated to this PR. I just noticed looking at linter errors that pie throws an error. Since it was a quick fix I decided to do it in this PR. techmix_company will be handled separately.
> Error handling

- src/js/techexposure_company.js
- src/routes/company_view.svelte
* techmix resizes to fit div it is in
* techmix technologies are ordered based on tech_order
> Resizing company techmix

- src/routes/+layout.svelte
> Remove ligt dark mode

- src/routes/company_view.svelte
- src/routes/portfolio_view.svelte
- src/routes/sector_view.svelte
I implement text provided by Nayra. PACTA intro will follow in a separate PR as it requires building an entire page.
NOTE: I expect changes in the text and layout but I'm implementing the current version as a starting point.
> Implement text analysts - portfolio, sector and company views

- src/routes/+layout.svelte
as opposed to the `RMI-PACTA` organization
> 📕 point GitHub link to this repo

- src/routes/+layout.svelte
- src/routes/company_view.svelte
- src/routes/portfolio_view.svelte
- src/routes/sector_view.svelte
rather than absolute!
Closes a bug introduced in #81
> 🐞 use relative data paths

- src/js/techmix_sector.js
I accidentally fully removed this in #100, when I intended to only remove the "let" portion of it :-D
> 🐛  add current year y axis labels

- src/routes/company_view.svelte
- src/routes/portfolio_view.svelte
- src/routes/sector_view.svelte
In this PR, I stream-line the text in all sections in alignment with @NAYRA-HERRERA's latest version of the copy document.
> ✨ streamline text for all sections

- src/js/time_line.js
> reverse the y-axis of emissions timeline so it's increasing

- .github/workflows/deploy.yml
Update GH Pages deploy action to allow for previews of PRs
You can see the preview from this branch via the comment below, to see #138 for an example of a PR with multiple text changes.
> Add PR Preview action for GH pages

- package.json
> 📝 `package.json` gains contributors fields

- README.md
Add common badges to the `README.md`, and update wording a bit
> 📝  update `README.md`

- src/js/techexposure_company.js
> remove trailing `.` from scenario label in techexposure_company.js

- .github/workflows/ci.yml
> `ci.yml` gains CRON schedule and workflow_dispatch

- src/js/included_table.js
> removed fixed width of "included table"

- src/js/techexposure_company.js
> Remove unnecessary part of company techmix footnote

- src/routes/about.svelte
As per instructions from Life IP.
> feat: gains link to Finance ClimAct website
