src/routes/+page.svelte, src/routes/executive_summary.svelte
This tab is not going to be part of this version of the dashboard.
=> Remove executive summary tab

src/js/techmix_sector.js
Add hover-overs with values for 'Scenario' and 'Benchmark' in techmix plot for quick reference which scenario and Benchmark the user is looking at.
=> Add hover over values to techmix labels

src/routes/sector_view.svelte
Closes #39 
* Wire up the selectors from landing page of the sector view 
* make the sector and asset class selectors data-driven. 
* remove 'Go' button from sector-view page (post landing) as it hinders user-experience
=> Wire up landing page

src/routes/sector_view.svelte
Make benchmark selector data-driven and change when one of these change:
* asset class
* sector
* equity market
My assumption is that only these influence the possible benchmark values but I might be wrong. Actually even the sector probably doesn't but I just add it as one of the 'top-level' filters.
=> Benchmark data-driven

src/routes/sector_view.svelte
In this PR I update two selectors
Scenario source dependent on:
* asset class
* sector
Equity market dependent on:
* asset class
* sector
I observed a weird behaviour when Automotive + Corporate bonds is selected but I believe this is due to lack of exposure to that sector/asset class combination in test portfolio. We need to investigate this further while testing and also implement a better solution when no data is present for a given combination of sector/asset class but that is a topic for another PR and I think it is captured by this PBI on ADO: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_sprints/taskboard/P4I/2DegreesInvesting/2024_22?workitem=11659
=> Scenario source and equity market selectors data driven

src/routes/sector_view.svelte
Only show volume trajectory div and fetch a plot when the chosen sector is a sector with technology pathway.
NOTE: some strange behaviour occurs when some combination of selectors is chosen but I believe it has nothing to do with this PR and is related to #59 . In some cases there is no data to fit the portfolio allocation selector and once that happens no plot that uses portfolio allocation can be drawn anymore because the value is `null`. This will be solved when implementing error handling and solving the bug.
=> Only show vol trajectory div for some sectors

src/css/plot_styles.css, src/js/included_table.js, src/routes/portfolio_view.svelte
Using the visual representation from the interactive report for now. Will try to make it visually more appealing later but it is already an improvement in terms of readability and the `null` values are not appearing anymore.
Closes #53
=> Improve table layout

src/js/included_table.js
This var was being defined for it's side effects, and is never actually called after being defined, causing the linter to complain. 
By removing the var definition, we still benefit from the desired side effects of calling each method on `rows`. 
You can confirm below that this is a pure refactor:
@MonikaFu FYI
Relates to #96 
Towards #29
=> 💄 included_table.js loses var `cells`

src/js/exposure_stats.js
This var was defined but never used, so I'm just removing it entirely.
You can confirm below that this is a pure refactor:
@MonikaFu FYI
Relates to #96 
Towards #29
=> 💄 exposure_stats.js loses var `marginRight`

src/routes/company_view.svelte, src/routes/portfolio_view.svelte, src/routes/sector_view.svelte
I did this by: 
- removing unused imports
- adding new imports (that were called but never correctly imported)
- logging all `err` vars to console (before doing this, I would get the unused var error
@MonikaFu FYI
Relates to #96 
Towards #29
=> 💄 ensure all svelte routes pass the linter

src/js/pie_exploded.js, src/js/techexposure.js, src/js/techexposure_company.js, src/js/techmix_sector.js, src/js/time_line.js, src/js/trajectory_alignment.js
This PR is where things get a little spicy. I am simply removing every `var` and `import` that is unused!
There are a few categories here:
- The simplest is just tech debt, a `var` or function argument was defined (and probably used at some point) and later removed from he function body, but left in the body
- `vars` that are defined for their side-effects (you can just remove them and call the methods alone)
- unused package imports (self explanatory)
This PR affects the following plots: 
- pie_exploded
- tech_exposure
- tech_exposure_company
- techmix_sector
- timeline
- trajectory_alignment
I will post side-by-sides of these plots before and after to show they still render (and I have visually inspected them to ensure all interactivity still functions as expected)
@MonikaFu FYI
Relates …
=> 💄 JS files lose all unused vars and imports

src/js/trajectory_alignment.js
Calls to `return` and `break` are superfluous (when you `return` you also automatically `break`), thus the `break` was unreachable code. 
While I was there, I also handled a refactor commented by a `TODO` in the code. 
@MonikaFu FYI
Relates to #96 
Towards #29
=> 💄 trajectory_alignment - remove unreachable code

src/js/exposure_stats.js
=> 💄 make asset class name bold in Exposure Stats

src/app.postcss, src/routes/+layout.svelte
This is a minor (and reversible) customization to get the application header aligned with RMI-style. 
Towards #91
=> 💄 App Bar header aligns with RMI colours

src/js/techexposure_company.js
- closes #93 
`scenario` and `scenario_source` capture the currently selected values of the scenario and scenario source selectors, so it's easy to utilize that here
unlike `data_up`, `subdata_up` does not contain any scenario information, so it cannot be taken from there (as I tried in #105)
`data_up` only contains one year, so it's still possible to pull the correct year from it as before
=> fix footnote to show correct scenario (techexp_comp)

.github/workflows/deploy.yml
Adds a small step to copy the `sample-data` back where we expect it. 
Broken by #109
(hard to test this one without merging it to `main` and seeing if the action works...)
=> 🐛 fix deploy action

src/js/pie_exploded.js
- closes #102
solved the 1st level `this` aliasing by passing through the index in each `.each()` loop and comparing the indices rather than comparing the elements (aliased `this`) themselves
otherwise follows suggestion in https://github.com/RMI-PACTA/pacta-dashboard-svelte/issues/102#issuecomment-2515396572
=> remove aliasing of `this`

.github/workflows/deploy.yml
Rather than copying the sample data to `static/data` (which would work prior to build), copy to `build/data`
=> 🔥 HOTFIX: Change path for copying sample data

.gitignore
For local development, it is easier to just dump testing data into the `static` directory, but don't want ot commit that!
Relates to #109
=> 🙈 ignore `static/data` directory

src/js/time_line.js
- closes #87 
Since the height is adaptive/relative, it made more sense to nudge the whole y-axis title down a bit.
=> nudege the y-axis title down on the emissions timeline

src/routes/company_view.svelte, src/routes/portfolio_view.svelte, src/routes/sector_view.svelte
This is just a proposal right now, but this allows users to view all plots at once in a simplified "Dashboard", while still allowing the flexibility to open further detailed on the plot when they are interested. 
Todo (if we decide we like this approach):
=> 🎨 present plot info in collapsible accordion element

src/routes/pacta_intro.svelte
Closes #131 
Closes #141 
Supersedes #139
=> 🎨 add accordion icons to intro tab

src/routes/portfolio_view.svelte
These data placeholders are meant to indicate values that are already clearly indicated in the plots themselves. 
Showing the same values twice is bad data story-telling practice and confusing to the user. 
Supersedes #122
=> 📝 remove superfluous data placeholders

src/routes/company_view.svelte, src/routes/pacta_intro.svelte, src/routes/portfolio_view.svelte, src/routes/sector_view.svelte
In this PR, I remove the superfluous "key features" sections, as well as a superfluous link to the "PACTA knowledge hub".
Towards getting the whole dashboard to be viewable in a single screen.
Closes #146 
Closes #147
=> 📝 remove key features bullets

src/app.postcss
- closes #94 
based on @jdhoffa's suggestion here https://github.com/RMI-PACTA/pacta-dashboard-svelte/issues/94#issuecomment-2515377985, with additional CSS to complete the job
⚠️ of course, this gets wonky if the browser window is narrow enough to make the header wrap the text and cause it to use an extra line... position relative to the header would be ideal, but not sure how to achieve that
=> fix tab bar position to the bottom of the header when scrolling

LICENSE
We only actually need the `LICENSE.md` here. 
The `LICENSE` file is superfluous, and is confusing GitHubs license detection process.
=> Delete `LICENSE` file

src/js/techexposure_company.js
aligns better with other plot labels, e.g. `* start date of the analysis`
=> don't use sentence-case in label that isn't a sentence

src/js/time_line.js
- closes #142
⚠️ maybe should dodge up instead of down so it doesn't overlap bottom x-axis tick marks?
⚠️ dodging dots on x-axis but not the line makes the dots seem disconnected from the line in some cases
=> dodge lines in emission intensity timeline plot

package-lock.json, package.json, src/app.postcss, src/css/plot_styles.css, src/js/createErrorMessageDiv.js, src/js/pie_exploded.js, src/rmi_theme.ts, src/routes/+layout.svelte, src/routes/company_view.svelte, src/routes/sector_view.svelte
Closes #91
* updated fonts
* updated theme colours to reflect RMI website
=> Update dashboard styling to be more RMI-like
